### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by guest2921** [leonv024/RAASNet#128]
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/kali/RAASNet/RAASNet.py", line 218, in login
    r = requests.post('https://zeznzo.nl/login.py', data=payload)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='zeznzo.nl', port=443): Max retries exceeded with url: /login.py (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))

**Comment by SimonPHP** [comment]
I have the same error, is this a python problem or a problem with the endpoint?
I tried it with Kali Linux and with Windows. Python 3.10 and Python 3.7.
