### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by vociczekonja** [leonv024/RAASNet#49]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\marko\AppData\Local\Microsoft\WindowsApps\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\marko\AppData\Local\Microsoft\WindowsApps\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\marko\OneDrive\Desktop\udarac\RAASNet\RAASNet.py", line 1281, in start_server
    self.server_socket.bind((host, port))
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by leonv024** [comment]
looks like you set a domain name as host, which it cannot resolve.
Try the IP instead. For example: instead of using localhost try 127.0.0.1.
