### ISSUE TITLE
Dynamic DNS

### ISSUE THREAD

**Issue by ahmedtsadek** [leonv024/RAASNet#5]
So i was trying to make it work with Dynamic DNS from noip but the server always gives error
the compiler works fine no error but each time i start the server it gives error even if i added my public ip it still gives error

`C:\Users\test\Desktop\RAASNet>python RAASNet.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "RAASNet.py", line 1116, in start_server
    self.server_socket.bind((host, port))
OSError: [WinError 10049] The requested address is not valid in its context

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "RAASNet.py", line 1116, in start_server
    self.server_socket.bind((host, port))
socket.gaierror: [Errno 11001] getaddrinfo failed

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "RAASNet.py", line 1116, in start_server
    self.server_socket.bind((host, port))
socket.gaierror: [Errno 11001] getaddrinfo failed

Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "RAASNet.py", line 1116, in start_server
    self.server_socket.bind((host, port))
OSError: [WinError 10049] The requested address is not valid in its context`

**Comment by leonv024** [comment]
You should not put your pub ip as host on the server, but your local IP.
The server will try to bind to the address on that interface on the local machine.

1:
You'll need to port forward the port on your router to, for example, 192.168.0.110 (local address) on port 8989 and then bind the server to 192.168.0.110. The firewall and/or router should send it there.

2:
With that said; the server doesn't translate domain addresses into IP addresses, because it should bind to a local address on that same system, not a pub.

3:
However, I didn't test the payload with a address as destination. Mainly because I don't think you would want to use it this way outside your network. I only tested it outside my network with a VPN.

4:
Note that the message the payload sends is plain-text and not encrypted.

I'll test  it (3) when I get home.

**Comment by ahmedtsadek** [comment]
Same for number 3 will test asap and report back to you also i am working on encrypting the data being sent until you open the pro version

**Comment by leonv024** [comment]
Hi there, me again.

I tested it.

You CAN put a domain name in your payload. It'll translate the IP address automatically.

I hope this answers your question.
