### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by lgren5** [leonv024/RAASNet#53]
$ python RAASNet.py
ERROR - Failed to import some modules.
No module named 'Crypto'
Traceback (most recent call last):
  File "F:\TEST\RAASNet\RAASNet.py", line 73, in <module>
    import pyaes
ModuleNotFoundError: No module named 'pyaes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\TEST\RAASNet\RAASNet.py", line 75, in <module>
    print('ERROR - Failed to import some modules.\n%s' % e)
NameError: name 'e' is not defined

**Comment by lgren5** [comment]
Now
$ python RAASNet.py
Traceback (most recent call last):
  File "F:\TEST\RAASNet\RAASNet.py", line 73, in <module>
    import pyaes
ModuleNotFoundError: No module named 'pyaes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\TEST\RAASNet\RAASNet.py", line 75, in <module>
    print('ERROR - Failed to import some modules.\n%s' % e)
NameError: name 'e' is not defined

**Comment by leonv024** [comment]
you likely forgot to install the modules with `pip3 install -r requirements`.
