### ISSUE TITLE
sh: 1: pyinstaller: not found

### ISSUE THREAD

**Issue by XKeyScore147** [leonv024/RAASNet#80]
┌──(kali㉿kali)-[~/RAASNet]
└─$ python3 RAASNet.py
Exception in thread Thread-1:
Traceback (most recent call last):                                                                                         
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner                                                    
    self.run()                                                                                                             
  File "/usr/lib/python3.9/threading.py", line 892, in run                                                                 
    self._target(*self._args, **self._kwargs)                                                                              
  File "/home/kali/RAASNet/RAASNet.py", line 1291, in start_server                                                         
    self.server_socket.bind((host, port))                                                                                  
PermissionError: [Errno 13] Permission denied                                                                              
sh: 1: pyinstaller: not found
sh: 1: pyinstaller: not found
  sh: 1: pyinstaller: not found
sh: 1: pyinstaller: not found

**Comment by XKeyScore147** [comment]
I was able to solve this by 

sudo apt install python3-pyinstaller
